### ISSUE TITLE
Fix the issue on startup.

### ISSUE THREAD

**Issue by nitingpt000** [piyush-1301/Trip#1]
**./src/component/info/Info.js
Module not found: Can't resolve 'date-fns' in '/home/nitinace/Desktop/Trip/src/component/info'**

Getting above error by the end of Sunday.

**Comment by piyush-1301** [comment]
I am not getting as such error.
but if you are getting this error you can type **npm i @date-io/date-fns@1.3.13** in your terminal 
or you can again download the ZIP file of this project and just type  **npm i**  

Netlify link of the project:- [https://trip-master.netlify.app](url)
